apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-serv-deployment
  namespace: car-serv
  labels:
    app: car-serv
spec:
  replicas: 2
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: car-serv
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: car-serv
    spec:
      containers:
        - name: car-serv
          image: elroydevops/car-serv
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
